name: pre-commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    uses: carlthome/workflows/.github/workflows/pre-commit.yaml@main
    with:
      update: ${{ github.event_name == 'schedule' }}
    permissions:
      contents: write
